# Generated by Django 3.2.7 on 2022-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid',
            field=models.CharField(choices=[('VALID', 'VALID'), ('INVALID', 'INVALID')], max_length=100, null=True),
        ),
    ]
